# Generated by Django 4.1.1 on 2023-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_group', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('benefits', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'npd_questionnaire',
                'managed': True,
            },
        ),
    ]
