# Generated by Django 5.0 on 2023-12-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'managed': False},
        ),
    ]
