version: "3.7"
services:
  app:
    build:
      context: "./app"
      dockerfile: "./Dockerfiles/Dockerfile"
    command: ["npm", "run", "dev"]
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - "./app:/usr/src/app"
      - /usr/src/app/node_modules
