FROM python:latest

WORKDIR  /usr/src/server

COPY . .

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y binutils libproj-dev gdal-bin

RUN pip config set global.trusted-host \
    "pypi.org files.pythonhosted.org pypi.python.org" \
    --trusted-host=pypi.python.org \
    --trusted-host=pypi.org \
    --trusted-host=files.pythonhosted.org
RUN pip3 install -r ./server/requirements.txt
